//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHub.Web.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoHub.Web.LanguageResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body style.
        /// </summary>
        public static string BodyStyleDisplayName {
            get {
                return ResourceManager.GetString("BodyStyleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string BrandDisplayName {
            get {
                return ResourceManager.GetString("BrandDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorDisplayName {
            get {
                return ResourceManager.GetString("ColorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string ConditionDisplayName {
            get {
                return ResourceManager.GetString("ConditionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionDisplayName {
            get {
                return ResourceManager.GetString("DescriptionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        public static string EngineDisplayName {
            get {
                return ResourceManager.GetString("EngineDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro standard.
        /// </summary>
        public static string EuroStandardDisplayName {
            get {
                return ResourceManager.GetString("EuroStandardDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Timing belt was changed 2 months ago. Insurance is paid up until next January. The car comes with four winter tires. There are some scratches on the back fender.
        /// </summary>
        public static string ExampleDescription {
            get {
                return ResourceManager.GetString("ExampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Opel Astra - Red - Great Condition.
        /// </summary>
        public static string ExampleTitle {
            get {
                return ResourceManager.GetString("ExampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string FieldIsRequiredErrorMessageFormat {
            get {
                return ResourceManager.GetString("FieldIsRequiredErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors count.
        /// </summary>
        public static string HasFourDoorsDisplayName {
            get {
                return ResourceManager.GetString("HasFourDoorsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse powers.
        /// </summary>
        public static string HorsePowersDisplayName {
            get {
                return ResourceManager.GetString("HorsePowersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid month.
        /// </summary>
        public static string InvalidMonthErrorMessage {
            get {
                return ResourceManager.GetString("InvalidMonthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}.
        /// </summary>
        public static string InvalidRangeErrorMessageFormat {
            get {
                return ResourceManager.GetString("InvalidRangeErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic exterior.
        /// </summary>
        public static string IsExteriorMetallicDisplayName {
            get {
                return ResourceManager.GetString("IsExteriorMetallicDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New import.
        /// </summary>
        public static string IsNewImportDisplayName {
            get {
                return ResourceManager.GetString("IsNewImportDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometrage.
        /// </summary>
        public static string KilometrageDisplayName {
            get {
                return ResourceManager.GetString("KilometrageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string ManufactureMonthDisplayName {
            get {
                return ResourceManager.GetString("ManufactureMonthDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string ManufactureYearDisplayName {
            get {
                return ResourceManager.GetString("ManufactureYearDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ModelDisplayName {
            get {
                return ResourceManager.GetString("ModelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PriceDisplayName {
            get {
                return ResourceManager.GetString("PriceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is negotiable.
        /// </summary>
        public static string PriceIsNegotiable {
            get {
                return ResourceManager.GetString("PriceIsNegotiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string RegionDisplayName {
            get {
                return ResourceManager.GetString("RegionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters.
        /// </summary>
        public static string StringExceedMaxLengthErrorMessageFormat {
            get {
                return ResourceManager.GetString("StringExceedMaxLengthErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length must be between {2} and {1}.
        /// </summary>
        public static string StringLengthErrorMessageFormat {
            get {
                return ResourceManager.GetString("StringLengthErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such {0} does not exist.
        /// </summary>
        public static string SuchItemDoesNotExistErrorMessageFormat {
            get {
                return ResourceManager.GetString("SuchItemDoesNotExistErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleDisplayName {
            get {
                return ResourceManager.GetString("TitleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string TownDisplayName {
            get {
                return ResourceManager.GetString("TownDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        public static string TransmissionDisplayName {
            get {
                return ResourceManager.GetString("TransmissionDisplayName", resourceCulture);
            }
        }
    }
}
